# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sparse_mask": "00_core.ipynb",
         "sparse_mask_like": "00_core.ipynb",
         "maybe_float": "00_core.ipynb",
         "sparse_params": "00_core.ipynb",
         "apply_masks": "00_core.ipynb",
         "is_sparseable_module": "00_core.ipynb",
         "sparseable_modules": "00_core.ipynb",
         "uniform_sparsity": "00_core.ipynb",
         "first_layer_dense_uniform": "00_core.ipynb",
         "erdos_renyi_sparsity": "00_core.ipynb",
         "sparsify_model": "00_core.ipynb",
         "random_score": "00_core.ipynb",
         "weight_magnitude": "00_core.ipynb",
         "gradient_magnitude": "00_core.ipynb",
         "gradient_momentum": "00_core.ipynb",
         "top_k_mask": "00_core.ipynb",
         "DynamicSparseTrainingCallback": "00_core.ipynb",
         "SET_presets": "00_core.ipynb",
         "SNFS_presets": "00_core.ipynb",
         "RigL_presets": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dcato98.github.io/fastsparse/"

git_url = "https://github.com/dcato98/fastsparse/tree/master/"

def custom_doc_links(name): return None
